// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240610004832_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("api.Models.Relic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AFFCT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ART")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CIV")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("FAME")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FTH")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Skill1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Skill2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Skill3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Special")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TECH")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Relics");
                });
#pragma warning restore 612, 618
        }
    }
}
